### ISSUE TITLE
Reset dndgrid plugin

### ISSUE THREAD

**Issue by aochoa017** [juji/dndgrid#1]
Hi!
This is simple but functional drag grid plugin.
But I need to reset dndgrid() when I add new div.dnd-gridcell by jquery append() function. Then I can't drag new item. Is it possible to do?

**Comment by juji** [comment]
Yes.. It's possible..
Just do another initialization:

e.g:
```
$('.dnd-gridcell').dndgrid({ 
    'trigger' : '.dnd-trigger' 
}); 
```

Only the new gridcells will be affected by Initialization.

**Comment by aochoa017** [comment]
I have revised my code and I had a mistake. Because of that, the initialization didn't work. Now it works perfectly.

Thanks
